# Generated by Django 6.0.3 on 2026-04-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='t1_houseinfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('HouseId', models.CharField(max_length=5)),
                ('HouseEstd', models.IntegerField()),
                ('HouseName', models.CharField(max_length=100)),
                ('HouseNameAlt', models.CharField(max_length=100)),
                ('HouseOffice', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('Building', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='t1_houseinfoalt',
            fields=[
                ('HID_id', models.AutoField(primary_key=True, serialize=False)),
                ('HouseName', models.CharField(max_length=100)),
                ('AltPhone', models.CharField(max_length=100)),
                ('AltEmail', models.CharField(max_length=100)),
            ],
        ),
    ]
