# Generated by Django 6.0.3 on 2026-04-03 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='t1_houseinfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('HouseId', models.IntegerField()),
                ('HouseEstd', models.IntegerField()),
                ('HouseName', models.CharField(max_length=100)),
                ('HouseNameAlt', models.CharField(max_length=100)),
                ('HouseOffice', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('Building', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='t1_houseinfoalt',
            fields=[
                ('HID_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='athleticsweb.t1_houseinfo')),
                ('HouseName', models.CharField(max_length=100)),
                ('AltPhone', models.CharField(blank=True, max_length=20, null=True)),
                ('AltEmail', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
