# Generated by Django 6.0.3 on 2026-04-04 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athleticsweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t1_houseinfoalt',
            name='HID_id',
            field=models.OneToOneField(db_column='HID_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='athleticsweb.t1_houseinfo'),
        ),
    ]
