# Generated by Django 6.0.3 on 2026-04-08 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athleticsweb', '0002_alter_t1_houseinfoalt_hid_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='t1_houseleaders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HouseName', models.CharField(max_length=100)),
                ('HCapID', models.CharField(max_length=100)),
                ('HouseCaptain', models.CharField(max_length=100)),
                ('HouseCaptainGrade', models.IntegerField(max_length=20)),
                ('HVCapID', models.CharField(max_length=100)),
                ('HouseViceCaptain', models.CharField(max_length=100)),
                ('HouseViceCaptainGrade', models.IntegerField(max_length=20)),
                ('CaptaincyTermStart', models.PositiveIntegerField()),
                ('CaptaincyTermEnd', models.PositiveIntegerField()),
                ('HID_id', models.ForeignKey(db_column='HID_id', on_delete=django.db.models.deletion.CASCADE, to='athleticsweb.t1_houseinfo')),
            ],
        ),
    ]
