# Generated by Django 6.0.3 on 2026-04-08 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athleticsweb', '0003_t1_houseleaders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t1_houseleaders',
            name='id',
        ),
        migrations.AlterField(
            model_name='t1_houseleaders',
            name='HID_id',
            field=models.OneToOneField(db_column='HID_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='athleticsweb.t1_houseinfo'),
        ),
    ]
