# Generated by Django 6.0.3 on 2026-04-09 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athleticsweb', '0004_remove_t1_houseleaders_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='t1_houseleaders',
            new_name='HouseLeader',
        ),
        migrations.CreateModel(
            name='SportsCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryId', models.CharField(max_length=100)),
                ('CategoryName', models.CharField(max_length=100)),
                ('GradeRangeJunior', models.CharField(max_length=100)),
                ('GradeRangeSenior', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trophy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Trophy', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='t1_houseinfoalt',
            new_name='HouseInfoAlt',
        ),
        migrations.RenameModel(
            old_name='t1_houseinfo',
            new_name='HouseInfo',
        ),
        migrations.CreateModel(
            name='CategoryIncharge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('InChargeGreen', models.CharField(max_length=100)),
                ('InchargePink', models.CharField(max_length=100)),
                ('InchargeBlue', models.CharField(max_length=100)),
                ('InchargeGold', models.CharField(max_length=100)),
                ('FacultyIncharge', models.CharField(max_length=100)),
                ('ID_id', models.ForeignKey(db_column='ID_id', on_delete=django.db.models.deletion.CASCADE, to='athleticsweb.sportscategory')),
            ],
        ),
        migrations.CreateModel(
            name='HIDinfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('HouseName', models.CharField(max_length=100)),
                ('HouseNameAlt', models.CharField(max_length=100)),
                ('trophies', models.ManyToManyField(related_name='houses', to='athleticsweb.trophy')),
            ],
        ),
    ]
