# Generated by Django 6.0.3 on 2026-04-09 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athleticsweb', '0005_houseleader_sportscategory_trophy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houseleader',
            name='HouseCaptainGrade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='houseleader',
            name='HouseViceCaptainGrade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sportscategory',
            name='GradeRangeJunior',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sportscategory',
            name='GradeRangeSenior',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
