# Generated by Django 6.0.3 on 2026-04-14 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athleticsweb', '0006_alter_houseleader_housecaptaingrade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportsFacility',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PracticeSchedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ScheduleDate', models.DateField()),
                ('ScheduleTime', models.TimeField()),
                ('categoryName_id', models.ForeignKey(db_column='categoryName_id', on_delete=django.db.models.deletion.CASCADE, to='athleticsweb.sportsfacility')),
            ],
        ),
    ]
