# Generated by Django 6.0.4 on 2026-04-14 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athleticsweb', '0007_sportsfacility_practiceschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsfacility',
            name='Location',
            field=models.CharField(choices=[('CampusPool', 'CampusPool'), ('BasketBallCourt', 'BasketBallCourt'), ('BackCompound', 'BackCompound'), ('TennisCourt', 'TennisCourt'), ('VolleyBallCourt', 'VolleyBallCourt')], max_length=100),
        ),
    ]
