# Generated by Django 6.0.4 on 2026-04-14 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athleticsweb', '0008_alter_sportsfacility_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
